version: '3'
services:
  php:
    image: php:8.4-fpm
    volumes:
      - .:/var/www/html
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network
networks:
  app-network:
    driver: bridge